### ISSUE TITLE
Video blog page

### ISSUE THREAD

**Issue by AmandaBekhoj** [mamont77/skillspeople#134]
I would also like a video blog page as we have on the salestribe.dk you think this is possible? :D

**Comment by mamont77** [comment]
I do not have time to do other tasks. Of course it is possible. :-D 
Do we finish this task #127 before?

**Comment by AmandaBekhoj** [comment]
i know you must be very busy!

start with task #127 and then move on the other task. 

i am sorry to ambush you with so much work at the same time!

**Comment by mamont77** [comment]
Please find the 10 differences. ;-)

http://www.salestribe.dk/video
http://www.skillspeople.dk/video

http://www.salestribe.dk/video/maanedens-salestriber-september-steffen-baekhoej
http://www.skillspeople.dk/video/phasellus-consectetuer-vestibulum-elit

If everything works as you want, you can add a "video" link to the navigation.

**Comment by AmandaBekhoj** [comment]
okay, i deleted the videos from slaestribe, to add the new ones, but i cannot see the 'add video' ? and also, i cannot seems to find where to edit the 'video overview' page, i need it to be located under the 'for kandidater' tap

**Comment by mamont77** [comment]
>>but i cannot see the 'add video'

added

>>i cannot seems to find where to edit the 'video overview' page

Sorry, I do not understand ((  Does it work on salestribe? Can you show?

>>i need it to be located under the 'for kandidater' tap

You or i add it later when video page will has a one video. Now this page is blank. Ok?

**Comment by AmandaBekhoj** [comment]
heh sorry, i meant i cannot se where i can edit www.skillspeople.dk/video in order to place it under the 'for kandidater' tap?

i have added the videos we have so far .. :))

**Comment by mamont77** [comment]
You can't edit www.skillspeople.dk/video because page rendered automaticaly.
You can edit video entity only, via http://www.skillspeople.dk/node/142/edit

>>to place it under the 'for kandidater' tap
Done:
http://www.skillspeople.dk/admin/structure/menu/manage/main-menu (added "video" to main menu)
http://www.skillspeople.dk/admin/structure/block/manage/menu/menu-for-kandidater/configure (added visibility "for-kandidater" block on video pages)
http://www.skillspeople.dk/admin/structure/menu/manage/menu-for-kandidater/list (added "video" to "for-kandidater" menu)

Have a nice evening ;-)

**Comment by AmandaBekhoj** [comment]
thanks, you are a superstar! have a nice evening too! :dancer:

**Comment by mamont77** [comment]
In what status this issue?

**Comment by AmandaBekhoj** [comment]
close, it seems to work :)
